apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  project: default 
  destination:
    namespace: my-app
    server: "https://kubernetes.default.svc"
  source:
    repoURL: https://gitlab.com/ProRocketeers/openalt-2025-examples.git
    targetRevision: HEAD
    path: 0_flight
    plugin:
      name: yokecd
      parameters:
        - name: wasm
          string: oci://ghcr.io/prorocketeers/openalt-2025-examples/flight:latest
        - name: inputFiles
          array:
            # paths are relative to `source.path`
            - input.yaml
        # ------------------
        # EXAMPLE ONLY
        - name: input
          map:
            # you can override/add any simple properties
            property: value
            newProperty: value
            # you can override/add nested properties
            nested.property: value
            # you can override array elements (with 0-based indices)
            array.0: value
            arrayOfObjects.0.property: value
            # you can append items to arrays with a special `-1` index (only once however, that would lead to duplicate keys in this map)
            arrayOfObjects.-1.property: value
            # in order to set more complex values, you can use JSON or YAML format (note the quotes or the `|` character)
            jsonObject: '{"some": "value"}'
            jsonObjectMultiline: |
              {
                "some": "value"
              }
            yamlObject: |
              some: value
              nested:
                value: foo
            # data types - booleans and numbers have to be quoted, but are parsed as respective types in the output JSON
            bool: "true"              # will turn into: "bool": true
            number: "42"              # will turn into: "number": 42
            # unless double quoted (then they're forced strings)
            boolString: '"true"'      # will turn into: "boolString": "true"
            numberString: '"42"'      # will turn into: "numberString": "42"
            # in YAML/JSON, the string quoting on booleans/numbers works normally, no need for additional quoting
            jsonTypes: |
              {
                "bool": true,
                "boolString": "true",
                "num": 42,
                "numString": "42"
              }
            yamlTypes: |
              bool: true
              boolString: "true"
              num: 42
              numString: "42"